export const content = {
  "translations": {
    "pt": {
      "start": "Começar trilha",
      "offline": "Missão fora da tela",
      "screen": "Missão na tela",
      "facilitator": "Assistente facilitador",
      "progress": "Progresso",
      "badge": "Conquista",
      "reflection": "Pergunta de roda"
    },
    "en": {
      "start": "Start track",
      "offline": "Off-screen mission",
      "screen": "Screen mission",
      "facilitator": "Facilitator assistant",
      "progress": "Progress",
      "badge": "Badge",
      "reflection": "Circle question"
    },
    "es": {
      "start": "Empezar ruta",
      "offline": "Misión fuera de pantalla",
      "screen": "Misión en pantalla",
      "facilitator": "Asistente facilitador",
      "progress": "Progreso",
      "badge": "Logro",
      "reflection": "Pregunta de ronda"
    }
  },
  "tracks": [
    {
      "id": "rural-kids",
      "age": "7-10",
      "context": "rural",
      "pt": "Pequenos Fazedores do Campo",
      "en": "Little Rural Makers",
      "es": "Pequeños Creadores del Campo",
      "tone": "brincalhão, simples, com exemplos de horta, feira, roça, animais, chuva e vizinhança",
      "missions": [
        {
          "id": "rural-kids-1",
          "phase": 1,
          "title": "Largada",
          "icon": "🚜",
          "goal": "entrar na jornada e entender que empreender é observar problemas e criar soluções úteis",
          "storyPt": "Hoje a turma abre uma portinha nova: olhar para feira da cidade com olhos de quem cuida, pergunta e cria. A ideia não é acertar de primeira. É reparar, testar e melhorar.",
          "screenPt": "Use o quadro da trilha para registrar uma descoberta, uma dúvida e uma pequena decisão do time.",
          "offlinePt": "Observe feira da cidade por 10 minutos sem celular. Anote no caderno: o que funciona, o que atrapalha e quem poderia ajudar.",
          "reflectionPt": "O que descobrimos que não sabíamos antes?",
          "aiPrepPt": "Ainda sem pedir resposta pronta para a IA: primeiro a turma observa e pergunta.",
          "badgePt": "Olhar Curioso",
          "scratchPt": "Usar Scratch só como desenho animado simples para contar o problema, se fizer sentido."
        },
        {
          "id": "rural-kids-2",
          "phase": 2,
          "title": "O que é empreender",
          "icon": "💡",
          "goal": "separar mito de realidade sobre empreender e valorizar persistência",
          "storyPt": "Hoje a turma abre uma portinha nova: olhar para horta da escola com olhos de quem cuida, pergunta e cria. A ideia não é acertar de primeira. É reparar, testar e melhorar.",
          "screenPt": "Use o quadro da trilha para registrar uma descoberta, uma dúvida e uma pequena decisão do time.",
          "offlinePt": "Observe horta da escola por 10 minutos sem celular. Anote no caderno: o que funciona, o que atrapalha e quem poderia ajudar.",
          "reflectionPt": "O que descobrimos que não sabíamos antes?",
          "aiPrepPt": "Ainda sem pedir resposta pronta para a IA: primeiro a turma observa e pergunta.",
          "badgePt": "Mão na Massa",
          "scratchPt": "Usar Scratch só como desenho animado simples para contar o problema, se fizer sentido."
        },
        {
          "id": "rural-kids-3",
          "phase": 3,
          "title": "Simulador",
          "icon": "🧭",
          "goal": "simular escolhas, consequências e combinados de equipe",
          "storyPt": "Hoje a turma abre uma portinha nova: olhar para galinheiro da vó com olhos de quem cuida, pergunta e cria. A ideia não é acertar de primeira. É reparar, testar e melhorar.",
          "screenPt": "Use o quadro da trilha para registrar uma descoberta, uma dúvida e uma pequena decisão do time.",
          "offlinePt": "Observe galinheiro da vó por 10 minutos sem celular. Anote no caderno: o que funciona, o que atrapalha e quem poderia ajudar.",
          "reflectionPt": "O que descobrimos que não sabíamos antes?",
          "aiPrepPt": "Ainda sem pedir resposta pronta para a IA: primeiro a turma observa e pergunta.",
          "badgePt": "Escuta Atenta",
          "scratchPt": "Usar Scratch só como desenho animado simples para contar o problema, se fizer sentido."
        },
        {
          "id": "rural-kids-4",
          "phase": 4,
          "title": "Desafios e times",
          "icon": "🤝",
          "goal": "formar times, escolher papéis e descobrir desafios próximos",
          "storyPt": "Hoje a turma abre uma portinha nova: olhar para trilha perto do bairro com olhos de quem cuida, pergunta e cria. A ideia não é acertar de primeira. É reparar, testar e melhorar.",
          "screenPt": "Use o quadro da trilha para registrar uma descoberta, uma dúvida e uma pequena decisão do time.",
          "offlinePt": "Observe trilha perto do bairro por 10 minutos sem celular. Anote no caderno: o que funciona, o que atrapalha e quem poderia ajudar.",
          "reflectionPt": "O que descobrimos que não sabíamos antes?",
          "aiPrepPt": "Ainda sem pedir resposta pronta para a IA: primeiro a turma observa e pergunta.",
          "badgePt": "Ideia Brotando",
          "scratchPt": "Usar Scratch só como desenho animado simples para contar o problema, se fizer sentido."
        },
        {
          "id": "rural-kids-5",
          "phase": 5,
          "title": "Empatia: ativar",
          "icon": "👂",
          "goal": "conversar com pessoas de verdade antes de inventar soluções",
          "storyPt": "Hoje a turma abre uma portinha nova: olhar para quitanda da praça com olhos de quem cuida, pergunta e cria. A ideia não é acertar de primeira. É reparar, testar e melhorar.",
          "screenPt": "Use o quadro da trilha para registrar uma descoberta, uma dúvida e uma pequena decisão do time.",
          "offlinePt": "Converse com alguém da família ou da comunidade sobre quitanda da praça. Traga uma frase, um desenho ou uma foto autorizada que mostre uma necessidade real.",
          "reflectionPt": "O que descobrimos que não sabíamos antes?",
          "aiPrepPt": "Ainda sem pedir resposta pronta para a IA: primeiro a turma observa e pergunta.",
          "badgePt": "Teste Corajoso",
          "scratchPt": "Usar Scratch só como desenho animado simples para contar o problema, se fizer sentido."
        },
        {
          "id": "rural-kids-6",
          "phase": 6,
          "title": "Insights",
          "icon": "🔎",
          "goal": "transformar escutas em descobertas claras",
          "storyPt": "Hoje a turma abre uma portinha nova: olhar para feira da cidade com olhos de quem cuida, pergunta e cria. A ideia não é acertar de primeira. É reparar, testar e melhorar.",
          "screenPt": "Use o quadro da trilha para registrar uma descoberta, uma dúvida e uma pequena decisão do time.",
          "offlinePt": "Converse com alguém da família ou da comunidade sobre feira da cidade. Traga uma frase, um desenho ou uma foto autorizada que mostre uma necessidade real.",
          "reflectionPt": "O que descobrimos que não sabíamos antes?",
          "aiPrepPt": "Ainda sem pedir resposta pronta para a IA: primeiro a turma observa e pergunta.",
          "badgePt": "Voz de Projeto",
          "scratchPt": "Usar Scratch só como desenho animado simples para contar o problema, se fizer sentido."
        },
        {
          "id": "rural-kids-7",
          "phase": 7,
          "title": "Tendo ideias",
          "icon": "🌱",
          "goal": "gerar muitas ideias e escolher uma com critérios simples",
          "storyPt": "Hoje a turma abre uma portinha nova: olhar para horta da escola com olhos de quem cuida, pergunta e cria. A ideia não é acertar de primeira. É reparar, testar e melhorar.",
          "screenPt": "Use o quadro da trilha para registrar uma descoberta, uma dúvida e uma pequena decisão do time.",
          "offlinePt": "Observe horta da escola por 10 minutos sem celular. Anote no caderno: o que funciona, o que atrapalha e quem poderia ajudar.",
          "reflectionPt": "O que descobrimos que não sabíamos antes?",
          "aiPrepPt": "Ainda sem pedir resposta pronta para a IA: primeiro a turma observa e pergunta.",
          "badgePt": "Olhar Curioso",
          "scratchPt": "Usar Scratch só como desenho animado simples para contar o problema, se fizer sentido."
        },
        {
          "id": "rural-kids-8",
          "phase": 8,
          "title": "Protótipo",
          "icon": "🛠️",
          "goal": "criar um primeiro protótipo em papel, Scratch ou encenação",
          "storyPt": "Hoje a turma abre uma portinha nova: olhar para galinheiro da vó com olhos de quem cuida, pergunta e cria. A ideia não é acertar de primeira. É reparar, testar e melhorar.",
          "screenPt": "Use o quadro da trilha para registrar uma descoberta, uma dúvida e uma pequena decisão do time.",
          "offlinePt": "Observe galinheiro da vó por 10 minutos sem celular. Anote no caderno: o que funciona, o que atrapalha e quem poderia ajudar.",
          "reflectionPt": "O que descobrimos que não sabíamos antes?",
          "aiPrepPt": "Peça ajuda da IA para organizar ideias, mas a decisão final precisa ser do time.",
          "badgePt": "Mão na Massa",
          "scratchPt": "Criar no Scratch uma tela com botão, personagem ou fluxo simples que represente a solução."
        },
        {
          "id": "rural-kids-9",
          "phase": 9,
          "title": "Canvas",
          "icon": "🗺️",
          "goal": "organizar proposta de valor, público, recursos e parceiros",
          "storyPt": "Hoje a turma abre uma portinha nova: olhar para trilha perto do bairro com olhos de quem cuida, pergunta e cria. A ideia não é acertar de primeira. É reparar, testar e melhorar.",
          "screenPt": "Use o quadro da trilha para registrar uma descoberta, uma dúvida e uma pequena decisão do time.",
          "offlinePt": "Observe trilha perto do bairro por 10 minutos sem celular. Anote no caderno: o que funciona, o que atrapalha e quem poderia ajudar.",
          "reflectionPt": "O que descobrimos que não sabíamos antes?",
          "aiPrepPt": "Peça ajuda da IA para organizar ideias, mas a decisão final precisa ser do time.",
          "badgePt": "Escuta Atenta",
          "scratchPt": "Criar no Scratch uma tela com botão, personagem ou fluxo simples que represente a solução."
        },
        {
          "id": "rural-kids-10",
          "phase": 10,
          "title": "Aprendendo com os testes",
          "icon": "🧪",
          "goal": "testar com usuários, ouvir críticas e melhorar sem drama",
          "storyPt": "Hoje a turma abre uma portinha nova: olhar para quitanda da praça com olhos de quem cuida, pergunta e cria. A ideia não é acertar de primeira. É reparar, testar e melhorar.",
          "screenPt": "Use o quadro da trilha para registrar uma descoberta, uma dúvida e uma pequena decisão do time.",
          "offlinePt": "Converse com alguém da família ou da comunidade sobre quitanda da praça. Traga uma frase, um desenho ou uma foto autorizada que mostre uma necessidade real.",
          "reflectionPt": "O que descobrimos que não sabíamos antes?",
          "aiPrepPt": "Peça ajuda da IA para organizar ideias, mas a decisão final precisa ser do time.",
          "badgePt": "Ideia Brotando",
          "scratchPt": "Criar no Scratch uma tela com botão, personagem ou fluxo simples que represente a solução."
        },
        {
          "id": "rural-kids-11",
          "phase": 11,
          "title": "Mutirão de criação",
          "icon": "⚡",
          "goal": "melhorar o protótipo em ritmo de mutirão",
          "storyPt": "Hoje a turma abre uma portinha nova: olhar para feira da cidade com olhos de quem cuida, pergunta e cria. A ideia não é acertar de primeira. É reparar, testar e melhorar.",
          "screenPt": "Use o quadro da trilha para registrar uma descoberta, uma dúvida e uma pequena decisão do time.",
          "offlinePt": "Observe feira da cidade por 10 minutos sem celular. Anote no caderno: o que funciona, o que atrapalha e quem poderia ajudar.",
          "reflectionPt": "O que descobrimos que não sabíamos antes?",
          "aiPrepPt": "Peça ajuda da IA para organizar ideias, mas a decisão final precisa ser do time.",
          "badgePt": "Teste Corajoso",
          "scratchPt": "Criar no Scratch uma tela com botão, personagem ou fluxo simples que represente a solução."
        },
        {
          "id": "rural-kids-12",
          "phase": 12,
          "title": "Preparando a apresentação",
          "icon": "🎤",
          "goal": "preparar uma fala curta, clara e honesta",
          "storyPt": "Hoje a turma abre uma portinha nova: olhar para horta da escola com olhos de quem cuida, pergunta e cria. A ideia não é acertar de primeira. É reparar, testar e melhorar.",
          "screenPt": "Use o quadro da trilha para registrar uma descoberta, uma dúvida e uma pequena decisão do time.",
          "offlinePt": "Observe horta da escola por 10 minutos sem celular. Anote no caderno: o que funciona, o que atrapalha e quem poderia ajudar.",
          "reflectionPt": "O que descobrimos que não sabíamos antes?",
          "aiPrepPt": "Peça ajuda da IA para organizar ideias, mas a decisão final precisa ser do time.",
          "badgePt": "Voz de Projeto",
          "scratchPt": "Criar no Scratch uma tela com botão, personagem ou fluxo simples que represente a solução."
        },
        {
          "id": "rural-kids-13",
          "phase": 13,
          "title": "Apresentação",
          "icon": "🎪",
          "goal": "apresentar a solução para a comunidade",
          "storyPt": "Hoje a turma abre uma portinha nova: olhar para galinheiro da vó com olhos de quem cuida, pergunta e cria. A ideia não é acertar de primeira. É reparar, testar e melhorar.",
          "screenPt": "Use o quadro da trilha para registrar uma descoberta, uma dúvida e uma pequena decisão do time.",
          "offlinePt": "Observe galinheiro da vó por 10 minutos sem celular. Anote no caderno: o que funciona, o que atrapalha e quem poderia ajudar.",
          "reflectionPt": "O que descobrimos que não sabíamos antes?",
          "aiPrepPt": "Peça ajuda da IA para organizar ideias, mas a decisão final precisa ser do time.",
          "badgePt": "Olhar Curioso",
          "scratchPt": "Criar no Scratch uma tela com botão, personagem ou fluxo simples que represente a solução."
        },
        {
          "id": "rural-kids-14",
          "phase": 14,
          "title": "E agora?",
          "icon": "🚀",
          "goal": "planejar próximos passos e celebrar aprendizados",
          "storyPt": "Hoje a turma abre uma portinha nova: olhar para trilha perto do bairro com olhos de quem cuida, pergunta e cria. A ideia não é acertar de primeira. É reparar, testar e melhorar.",
          "screenPt": "Use o quadro da trilha para registrar uma descoberta, uma dúvida e uma pequena decisão do time.",
          "offlinePt": "Observe trilha perto do bairro por 10 minutos sem celular. Anote no caderno: o que funciona, o que atrapalha e quem poderia ajudar.",
          "reflectionPt": "O que descobrimos que não sabíamos antes?",
          "aiPrepPt": "Peça ajuda da IA para organizar ideias, mas a decisão final precisa ser do time.",
          "badgePt": "Mão na Massa",
          "scratchPt": "Criar no Scratch uma tela com botão, personagem ou fluxo simples que represente a solução."
        }
      ]
    },
    {
      "id": "urban-kids",
      "age": "7-10",
      "context": "urban",
      "pt": "Pequenos Fazedores da Cidade",
      "en": "Little City Makers",
      "es": "Pequeños Creadores de la Ciudad",
      "tone": "brincalhão, simples, com exemplos de bairro, escola, praça, transporte, comércio local e família",
      "missions": [
        {
          "id": "urban-kids-1",
          "phase": 1,
          "title": "Largada",
          "icon": "🚜",
          "goal": "entrar na jornada e entender que empreender é observar problemas e criar soluções úteis",
          "storyPt": "Hoje a turma abre uma portinha nova: olhar para cantina da escola com olhos de quem cuida, pergunta e cria. A ideia não é acertar de primeira. É reparar, testar e melhorar.",
          "screenPt": "Use o quadro da trilha para registrar uma descoberta, uma dúvida e uma pequena decisão do time.",
          "offlinePt": "Observe cantina da escola por 10 minutos sem celular. Anote no caderno: o que funciona, o que atrapalha e quem poderia ajudar.",
          "reflectionPt": "O que descobrimos que não sabíamos antes?",
          "aiPrepPt": "Ainda sem pedir resposta pronta para a IA: primeiro a turma observa e pergunta.",
          "badgePt": "Olhar Curioso",
          "scratchPt": "Usar Scratch só como desenho animado simples para contar o problema, se fizer sentido."
        },
        {
          "id": "urban-kids-2",
          "phase": 2,
          "title": "O que é empreender",
          "icon": "💡",
          "goal": "separar mito de realidade sobre empreender e valorizar persistência",
          "storyPt": "Hoje a turma abre uma portinha nova: olhar para praça do bairro com olhos de quem cuida, pergunta e cria. A ideia não é acertar de primeira. É reparar, testar e melhorar.",
          "screenPt": "Use o quadro da trilha para registrar uma descoberta, uma dúvida e uma pequena decisão do time.",
          "offlinePt": "Observe praça do bairro por 10 minutos sem celular. Anote no caderno: o que funciona, o que atrapalha e quem poderia ajudar.",
          "reflectionPt": "O que descobrimos que não sabíamos antes?",
          "aiPrepPt": "Ainda sem pedir resposta pronta para a IA: primeiro a turma observa e pergunta.",
          "badgePt": "Mão na Massa",
          "scratchPt": "Usar Scratch só como desenho animado simples para contar o problema, se fizer sentido."
        },
        {
          "id": "urban-kids-3",
          "phase": 3,
          "title": "Simulador",
          "icon": "🧭",
          "goal": "simular escolhas, consequências e combinados de equipe",
          "storyPt": "Hoje a turma abre uma portinha nova: olhar para ônibus lotado com olhos de quem cuida, pergunta e cria. A ideia não é acertar de primeira. É reparar, testar e melhorar.",
          "screenPt": "Use o quadro da trilha para registrar uma descoberta, uma dúvida e uma pequena decisão do time.",
          "offlinePt": "Observe ônibus lotado por 10 minutos sem celular. Anote no caderno: o que funciona, o que atrapalha e quem poderia ajudar.",
          "reflectionPt": "O que descobrimos que não sabíamos antes?",
          "aiPrepPt": "Ainda sem pedir resposta pronta para a IA: primeiro a turma observa e pergunta.",
          "badgePt": "Escuta Atenta",
          "scratchPt": "Usar Scratch só como desenho animado simples para contar o problema, se fizer sentido."
        },
        {
          "id": "urban-kids-4",
          "phase": 4,
          "title": "Desafios e times",
          "icon": "🤝",
          "goal": "formar times, escolher papéis e descobrir desafios próximos",
          "storyPt": "Hoje a turma abre uma portinha nova: olhar para mercadinho da esquina com olhos de quem cuida, pergunta e cria. A ideia não é acertar de primeira. É reparar, testar e melhorar.",
          "screenPt": "Use o quadro da trilha para registrar uma descoberta, uma dúvida e uma pequena decisão do time.",
          "offlinePt": "Observe mercadinho da esquina por 10 minutos sem celular. Anote no caderno: o que funciona, o que atrapalha e quem poderia ajudar.",
          "reflectionPt": "O que descobrimos que não sabíamos antes?",
          "aiPrepPt": "Ainda sem pedir resposta pronta para a IA: primeiro a turma observa e pergunta.",
          "badgePt": "Ideia Brotando",
          "scratchPt": "Usar Scratch só como desenho animado simples para contar o problema, se fizer sentido."
        },
        {
          "id": "urban-kids-5",
          "phase": 5,
          "title": "Empatia: ativar",
          "icon": "👂",
          "goal": "conversar com pessoas de verdade antes de inventar soluções",
          "storyPt": "Hoje a turma abre uma portinha nova: olhar para biblioteca comunitária com olhos de quem cuida, pergunta e cria. A ideia não é acertar de primeira. É reparar, testar e melhorar.",
          "screenPt": "Use o quadro da trilha para registrar uma descoberta, uma dúvida e uma pequena decisão do time.",
          "offlinePt": "Converse com alguém da família ou da comunidade sobre biblioteca comunitária. Traga uma frase, um desenho ou uma foto autorizada que mostre uma necessidade real.",
          "reflectionPt": "O que descobrimos que não sabíamos antes?",
          "aiPrepPt": "Ainda sem pedir resposta pronta para a IA: primeiro a turma observa e pergunta.",
          "badgePt": "Teste Corajoso",
          "scratchPt": "Usar Scratch só como desenho animado simples para contar o problema, se fizer sentido."
        },
        {
          "id": "urban-kids-6",
          "phase": 6,
          "title": "Insights",
          "icon": "🔎",
          "goal": "transformar escutas em descobertas claras",
          "storyPt": "Hoje a turma abre uma portinha nova: olhar para cantina da escola com olhos de quem cuida, pergunta e cria. A ideia não é acertar de primeira. É reparar, testar e melhorar.",
          "screenPt": "Use o quadro da trilha para registrar uma descoberta, uma dúvida e uma pequena decisão do time.",
          "offlinePt": "Converse com alguém da família ou da comunidade sobre cantina da escola. Traga uma frase, um desenho ou uma foto autorizada que mostre uma necessidade real.",
          "reflectionPt": "O que descobrimos que não sabíamos antes?",
          "aiPrepPt": "Ainda sem pedir resposta pronta para a IA: primeiro a turma observa e pergunta.",
          "badgePt": "Voz de Projeto",
          "scratchPt": "Usar Scratch só como desenho animado simples para contar o problema, se fizer sentido."
        },
        {
          "id": "urban-kids-7",
          "phase": 7,
          "title": "Tendo ideias",
          "icon": "🌱",
          "goal": "gerar muitas ideias e escolher uma com critérios simples",
          "storyPt": "Hoje a turma abre uma portinha nova: olhar para praça do bairro com olhos de quem cuida, pergunta e cria. A ideia não é acertar de primeira. É reparar, testar e melhorar.",
          "screenPt": "Use o quadro da trilha para registrar uma descoberta, uma dúvida e uma pequena decisão do time.",
          "offlinePt": "Observe praça do bairro por 10 minutos sem celular. Anote no caderno: o que funciona, o que atrapalha e quem poderia ajudar.",
          "reflectionPt": "O que descobrimos que não sabíamos antes?",
          "aiPrepPt": "Ainda sem pedir resposta pronta para a IA: primeiro a turma observa e pergunta.",
          "badgePt": "Olhar Curioso",
          "scratchPt": "Usar Scratch só como desenho animado simples para contar o problema, se fizer sentido."
        },
        {
          "id": "urban-kids-8",
          "phase": 8,
          "title": "Protótipo",
          "icon": "🛠️",
          "goal": "criar um primeiro protótipo em papel, Scratch ou encenação",
          "storyPt": "Hoje a turma abre uma portinha nova: olhar para ônibus lotado com olhos de quem cuida, pergunta e cria. A ideia não é acertar de primeira. É reparar, testar e melhorar.",
          "screenPt": "Use o quadro da trilha para registrar uma descoberta, uma dúvida e uma pequena decisão do time.",
          "offlinePt": "Observe ônibus lotado por 10 minutos sem celular. Anote no caderno: o que funciona, o que atrapalha e quem poderia ajudar.",
          "reflectionPt": "O que descobrimos que não sabíamos antes?",
          "aiPrepPt": "Peça ajuda da IA para organizar ideias, mas a decisão final precisa ser do time.",
          "badgePt": "Mão na Massa",
          "scratchPt": "Criar no Scratch uma tela com botão, personagem ou fluxo simples que represente a solução."
        },
        {
          "id": "urban-kids-9",
          "phase": 9,
          "title": "Canvas",
          "icon": "🗺️",
          "goal": "organizar proposta de valor, público, recursos e parceiros",
          "storyPt": "Hoje a turma abre uma portinha nova: olhar para mercadinho da esquina com olhos de quem cuida, pergunta e cria. A ideia não é acertar de primeira. É reparar, testar e melhorar.",
          "screenPt": "Use o quadro da trilha para registrar uma descoberta, uma dúvida e uma pequena decisão do time.",
          "offlinePt": "Observe mercadinho da esquina por 10 minutos sem celular. Anote no caderno: o que funciona, o que atrapalha e quem poderia ajudar.",
          "reflectionPt": "O que descobrimos que não sabíamos antes?",
          "aiPrepPt": "Peça ajuda da IA para organizar ideias, mas a decisão final precisa ser do time.",
          "badgePt": "Escuta Atenta",
          "scratchPt": "Criar no Scratch uma tela com botão, personagem ou fluxo simples que represente a solução."
        },
        {
          "id": "urban-kids-10",
          "phase": 10,
          "title": "Aprendendo com os testes",
          "icon": "🧪",
          "goal": "testar com usuários, ouvir críticas e melhorar sem drama",
          "storyPt": "Hoje a turma abre uma portinha nova: olhar para biblioteca comunitária com olhos de quem cuida, pergunta e cria. A ideia não é acertar de primeira. É reparar, testar e melhorar.",
          "screenPt": "Use o quadro da trilha para registrar uma descoberta, uma dúvida e uma pequena decisão do time.",
          "offlinePt": "Converse com alguém da família ou da comunidade sobre biblioteca comunitária. Traga uma frase, um desenho ou uma foto autorizada que mostre uma necessidade real.",
          "reflectionPt": "O que descobrimos que não sabíamos antes?",
          "aiPrepPt": "Peça ajuda da IA para organizar ideias, mas a decisão final precisa ser do time.",
          "badgePt": "Ideia Brotando",
          "scratchPt": "Criar no Scratch uma tela com botão, personagem ou fluxo simples que represente a solução."
        },
        {
          "id": "urban-kids-11",
          "phase": 11,
          "title": "Mutirão de criação",
          "icon": "⚡",
          "goal": "melhorar o protótipo em ritmo de mutirão",
          "storyPt": "Hoje a turma abre uma portinha nova: olhar para cantina da escola com olhos de quem cuida, pergunta e cria. A ideia não é acertar de primeira. É reparar, testar e melhorar.",
          "screenPt": "Use o quadro da trilha para registrar uma descoberta, uma dúvida e uma pequena decisão do time.",
          "offlinePt": "Observe cantina da escola por 10 minutos sem celular. Anote no caderno: o que funciona, o que atrapalha e quem poderia ajudar.",
          "reflectionPt": "O que descobrimos que não sabíamos antes?",
          "aiPrepPt": "Peça ajuda da IA para organizar ideias, mas a decisão final precisa ser do time.",
          "badgePt": "Teste Corajoso",
          "scratchPt": "Criar no Scratch uma tela com botão, personagem ou fluxo simples que represente a solução."
        },
        {
          "id": "urban-kids-12",
          "phase": 12,
          "title": "Preparando a apresentação",
          "icon": "🎤",
          "goal": "preparar uma fala curta, clara e honesta",
          "storyPt": "Hoje a turma abre uma portinha nova: olhar para praça do bairro com olhos de quem cuida, pergunta e cria. A ideia não é acertar de primeira. É reparar, testar e melhorar.",
          "screenPt": "Use o quadro da trilha para registrar uma descoberta, uma dúvida e uma pequena decisão do time.",
          "offlinePt": "Observe praça do bairro por 10 minutos sem celular. Anote no caderno: o que funciona, o que atrapalha e quem poderia ajudar.",
          "reflectionPt": "O que descobrimos que não sabíamos antes?",
          "aiPrepPt": "Peça ajuda da IA para organizar ideias, mas a decisão final precisa ser do time.",
          "badgePt": "Voz de Projeto",
          "scratchPt": "Criar no Scratch uma tela com botão, personagem ou fluxo simples que represente a solução."
        },
        {
          "id": "urban-kids-13",
          "phase": 13,
          "title": "Apresentação",
          "icon": "🎪",
          "goal": "apresentar a solução para a comunidade",
          "storyPt": "Hoje a turma abre uma portinha nova: olhar para ônibus lotado com olhos de quem cuida, pergunta e cria. A ideia não é acertar de primeira. É reparar, testar e melhorar.",
          "screenPt": "Use o quadro da trilha para registrar uma descoberta, uma dúvida e uma pequena decisão do time.",
          "offlinePt": "Observe ônibus lotado por 10 minutos sem celular. Anote no caderno: o que funciona, o que atrapalha e quem poderia ajudar.",
          "reflectionPt": "O que descobrimos que não sabíamos antes?",
          "aiPrepPt": "Peça ajuda da IA para organizar ideias, mas a decisão final precisa ser do time.",
          "badgePt": "Olhar Curioso",
          "scratchPt": "Criar no Scratch uma tela com botão, personagem ou fluxo simples que represente a solução."
        },
        {
          "id": "urban-kids-14",
          "phase": 14,
          "title": "E agora?",
          "icon": "🚀",
          "goal": "planejar próximos passos e celebrar aprendizados",
          "storyPt": "Hoje a turma abre uma portinha nova: olhar para mercadinho da esquina com olhos de quem cuida, pergunta e cria. A ideia não é acertar de primeira. É reparar, testar e melhorar.",
          "screenPt": "Use o quadro da trilha para registrar uma descoberta, uma dúvida e uma pequena decisão do time.",
          "offlinePt": "Observe mercadinho da esquina por 10 minutos sem celular. Anote no caderno: o que funciona, o que atrapalha e quem poderia ajudar.",
          "reflectionPt": "O que descobrimos que não sabíamos antes?",
          "aiPrepPt": "Peça ajuda da IA para organizar ideias, mas a decisão final precisa ser do time.",
          "badgePt": "Mão na Massa",
          "scratchPt": "Criar no Scratch uma tela com botão, personagem ou fluxo simples que represente a solução."
        }
      ]
    },
    {
      "id": "rural-youth",
      "age": "12-14",
      "context": "rural",
      "pt": "Jovens Inovadores do Campo",
      "en": "Young Rural Innovators",
      "es": "Jóvenes Innovadores del Campo",
      "tone": "direto, curioso, com desafios reais de produção, turismo, clima, feira, logística e comunidade",
      "missions": [
        {
          "id": "rural-youth-1",
          "phase": 1,
          "title": "Largada",
          "icon": "🚜",
          "goal": "entrar na jornada e entender que empreender é observar problemas e criar soluções úteis",
          "storyPt": "Hoje a turma abre uma portinha nova: olhar para turismo de cachoeira com olhos de quem cuida, pergunta e cria. A ideia não é acertar de primeira. É reparar, testar e melhorar.",
          "screenPt": "Registre hipóteses, evidências e decisões no painel do projeto. Depois escolha uma ação pequena para validar.",
          "offlinePt": "Observe turismo de cachoeira por 10 minutos sem celular. Anote no caderno: o que funciona, o que atrapalha e quem poderia ajudar.",
          "reflectionPt": "O que descobrimos que não sabíamos antes?",
          "aiPrepPt": "Ainda sem pedir resposta pronta para a IA: primeiro a turma observa e pergunta.",
          "badgePt": "Olhar Curioso",
          "scratchPt": "Usar Scratch só como desenho animado simples para contar o problema, se fizer sentido."
        },
        {
          "id": "rural-youth-2",
          "phase": 2,
          "title": "O que é empreender",
          "icon": "💡",
          "goal": "separar mito de realidade sobre empreender e valorizar persistência",
          "storyPt": "Hoje a turma abre uma portinha nova: olhar para escoamento da produção com olhos de quem cuida, pergunta e cria. A ideia não é acertar de primeira. É reparar, testar e melhorar.",
          "screenPt": "Registre hipóteses, evidências e decisões no painel do projeto. Depois escolha uma ação pequena para validar.",
          "offlinePt": "Observe escoamento da produção por 10 minutos sem celular. Anote no caderno: o que funciona, o que atrapalha e quem poderia ajudar.",
          "reflectionPt": "O que descobrimos que não sabíamos antes?",
          "aiPrepPt": "Ainda sem pedir resposta pronta para a IA: primeiro a turma observa e pergunta.",
          "badgePt": "Mão na Massa",
          "scratchPt": "Usar Scratch só como desenho animado simples para contar o problema, se fizer sentido."
        },
        {
          "id": "rural-youth-3",
          "phase": 3,
          "title": "Simulador",
          "icon": "🧭",
          "goal": "simular escolhas, consequências e combinados de equipe",
          "storyPt": "Hoje a turma abre uma portinha nova: olhar para previsão de chuva com olhos de quem cuida, pergunta e cria. A ideia não é acertar de primeira. É reparar, testar e melhorar.",
          "screenPt": "Registre hipóteses, evidências e decisões no painel do projeto. Depois escolha uma ação pequena para validar.",
          "offlinePt": "Observe previsão de chuva por 10 minutos sem celular. Anote no caderno: o que funciona, o que atrapalha e quem poderia ajudar.",
          "reflectionPt": "O que descobrimos que não sabíamos antes?",
          "aiPrepPt": "Ainda sem pedir resposta pronta para a IA: primeiro a turma observa e pergunta.",
          "badgePt": "Escuta Atenta",
          "scratchPt": "Usar Scratch só como desenho animado simples para contar o problema, se fizer sentido."
        },
        {
          "id": "rural-youth-4",
          "phase": 4,
          "title": "Desafios e times",
          "icon": "🤝",
          "goal": "formar times, escolher papéis e descobrir desafios próximos",
          "storyPt": "Hoje a turma abre uma portinha nova: olhar para feira de produtores com olhos de quem cuida, pergunta e cria. A ideia não é acertar de primeira. É reparar, testar e melhorar.",
          "screenPt": "Registre hipóteses, evidências e decisões no painel do projeto. Depois escolha uma ação pequena para validar.",
          "offlinePt": "Observe feira de produtores por 10 minutos sem celular. Anote no caderno: o que funciona, o que atrapalha e quem poderia ajudar.",
          "reflectionPt": "O que descobrimos que não sabíamos antes?",
          "aiPrepPt": "Ainda sem pedir resposta pronta para a IA: primeiro a turma observa e pergunta.",
          "badgePt": "Ideia Brotando",
          "scratchPt": "Usar Scratch só como desenho animado simples para contar o problema, se fizer sentido."
        },
        {
          "id": "rural-youth-5",
          "phase": 5,
          "title": "Empatia: ativar",
          "icon": "👂",
          "goal": "conversar com pessoas de verdade antes de inventar soluções",
          "storyPt": "Hoje a turma abre uma portinha nova: olhar para reserva de ferramentas com olhos de quem cuida, pergunta e cria. A ideia não é acertar de primeira. É reparar, testar e melhorar.",
          "screenPt": "Registre hipóteses, evidências e decisões no painel do projeto. Depois escolha uma ação pequena para validar.",
          "offlinePt": "Converse com alguém da família ou da comunidade sobre reserva de ferramentas. Traga uma frase, um desenho ou uma foto autorizada que mostre uma necessidade real.",
          "reflectionPt": "O que descobrimos que não sabíamos antes?",
          "aiPrepPt": "Ainda sem pedir resposta pronta para a IA: primeiro a turma observa e pergunta.",
          "badgePt": "Teste Corajoso",
          "scratchPt": "Usar Scratch só como desenho animado simples para contar o problema, se fizer sentido."
        },
        {
          "id": "rural-youth-6",
          "phase": 6,
          "title": "Insights",
          "icon": "🔎",
          "goal": "transformar escutas em descobertas claras",
          "storyPt": "Hoje a turma abre uma portinha nova: olhar para turismo de cachoeira com olhos de quem cuida, pergunta e cria. A ideia não é acertar de primeira. É reparar, testar e melhorar.",
          "screenPt": "Registre hipóteses, evidências e decisões no painel do projeto. Depois escolha uma ação pequena para validar.",
          "offlinePt": "Converse com alguém da família ou da comunidade sobre turismo de cachoeira. Traga uma frase, um desenho ou uma foto autorizada que mostre uma necessidade real.",
          "reflectionPt": "O que descobrimos que não sabíamos antes?",
          "aiPrepPt": "Ainda sem pedir resposta pronta para a IA: primeiro a turma observa e pergunta.",
          "badgePt": "Voz de Projeto",
          "scratchPt": "Usar Scratch só como desenho animado simples para contar o problema, se fizer sentido."
        },
        {
          "id": "rural-youth-7",
          "phase": 7,
          "title": "Tendo ideias",
          "icon": "🌱",
          "goal": "gerar muitas ideias e escolher uma com critérios simples",
          "storyPt": "Hoje a turma abre uma portinha nova: olhar para escoamento da produção com olhos de quem cuida, pergunta e cria. A ideia não é acertar de primeira. É reparar, testar e melhorar.",
          "screenPt": "Registre hipóteses, evidências e decisões no painel do projeto. Depois escolha uma ação pequena para validar.",
          "offlinePt": "Observe escoamento da produção por 10 minutos sem celular. Anote no caderno: o que funciona, o que atrapalha e quem poderia ajudar.",
          "reflectionPt": "O que descobrimos que não sabíamos antes?",
          "aiPrepPt": "Ainda sem pedir resposta pronta para a IA: primeiro a turma observa e pergunta.",
          "badgePt": "Olhar Curioso",
          "scratchPt": "Usar Scratch só como desenho animado simples para contar o problema, se fizer sentido."
        },
        {
          "id": "rural-youth-8",
          "phase": 8,
          "title": "Protótipo",
          "icon": "🛠️",
          "goal": "criar um primeiro protótipo em papel, Scratch ou encenação",
          "storyPt": "Hoje a turma abre uma portinha nova: olhar para previsão de chuva com olhos de quem cuida, pergunta e cria. A ideia não é acertar de primeira. É reparar, testar e melhorar.",
          "screenPt": "Registre hipóteses, evidências e decisões no painel do projeto. Depois escolha uma ação pequena para validar.",
          "offlinePt": "Observe previsão de chuva por 10 minutos sem celular. Anote no caderno: o que funciona, o que atrapalha e quem poderia ajudar.",
          "reflectionPt": "O que descobrimos que não sabíamos antes?",
          "aiPrepPt": "Peça ajuda da IA para organizar ideias, mas a decisão final precisa ser do time.",
          "badgePt": "Mão na Massa",
          "scratchPt": "Criar no Scratch uma tela com botão, personagem ou fluxo simples que represente a solução."
        },
        {
          "id": "rural-youth-9",
          "phase": 9,
          "title": "Canvas",
          "icon": "🗺️",
          "goal": "organizar proposta de valor, público, recursos e parceiros",
          "storyPt": "Hoje a turma abre uma portinha nova: olhar para feira de produtores com olhos de quem cuida, pergunta e cria. A ideia não é acertar de primeira. É reparar, testar e melhorar.",
          "screenPt": "Registre hipóteses, evidências e decisões no painel do projeto. Depois escolha uma ação pequena para validar.",
          "offlinePt": "Observe feira de produtores por 10 minutos sem celular. Anote no caderno: o que funciona, o que atrapalha e quem poderia ajudar.",
          "reflectionPt": "O que descobrimos que não sabíamos antes?",
          "aiPrepPt": "Peça ajuda da IA para organizar ideias, mas a decisão final precisa ser do time.",
          "badgePt": "Escuta Atenta",
          "scratchPt": "Criar no Scratch uma tela com botão, personagem ou fluxo simples que represente a solução."
        },
        {
          "id": "rural-youth-10",
          "phase": 10,
          "title": "Aprendendo com os testes",
          "icon": "🧪",
          "goal": "testar com usuários, ouvir críticas e melhorar sem drama",
          "storyPt": "Hoje a turma abre uma portinha nova: olhar para reserva de ferramentas com olhos de quem cuida, pergunta e cria. A ideia não é acertar de primeira. É reparar, testar e melhorar.",
          "screenPt": "Registre hipóteses, evidências e decisões no painel do projeto. Depois escolha uma ação pequena para validar.",
          "offlinePt": "Converse com alguém da família ou da comunidade sobre reserva de ferramentas. Traga uma frase, um desenho ou uma foto autorizada que mostre uma necessidade real.",
          "reflectionPt": "O que descobrimos que não sabíamos antes?",
          "aiPrepPt": "Peça ajuda da IA para organizar ideias, mas a decisão final precisa ser do time.",
          "badgePt": "Ideia Brotando",
          "scratchPt": "Criar no Scratch uma tela com botão, personagem ou fluxo simples que represente a solução."
        },
        {
          "id": "rural-youth-11",
          "phase": 11,
          "title": "Mutirão de criação",
          "icon": "⚡",
          "goal": "melhorar o protótipo em ritmo de mutirão",
          "storyPt": "Hoje a turma abre uma portinha nova: olhar para turismo de cachoeira com olhos de quem cuida, pergunta e cria. A ideia não é acertar de primeira. É reparar, testar e melhorar.",
          "screenPt": "Registre hipóteses, evidências e decisões no painel do projeto. Depois escolha uma ação pequena para validar.",
          "offlinePt": "Observe turismo de cachoeira por 10 minutos sem celular. Anote no caderno: o que funciona, o que atrapalha e quem poderia ajudar.",
          "reflectionPt": "O que descobrimos que não sabíamos antes?",
          "aiPrepPt": "Peça ajuda da IA para organizar ideias, mas a decisão final precisa ser do time.",
          "badgePt": "Teste Corajoso",
          "scratchPt": "Criar no Scratch uma tela com botão, personagem ou fluxo simples que represente a solução."
        },
        {
          "id": "rural-youth-12",
          "phase": 12,
          "title": "Preparando a apresentação",
          "icon": "🎤",
          "goal": "preparar uma fala curta, clara e honesta",
          "storyPt": "Hoje a turma abre uma portinha nova: olhar para escoamento da produção com olhos de quem cuida, pergunta e cria. A ideia não é acertar de primeira. É reparar, testar e melhorar.",
          "screenPt": "Registre hipóteses, evidências e decisões no painel do projeto. Depois escolha uma ação pequena para validar.",
          "offlinePt": "Observe escoamento da produção por 10 minutos sem celular. Anote no caderno: o que funciona, o que atrapalha e quem poderia ajudar.",
          "reflectionPt": "O que descobrimos que não sabíamos antes?",
          "aiPrepPt": "Peça ajuda da IA para organizar ideias, mas a decisão final precisa ser do time.",
          "badgePt": "Voz de Projeto",
          "scratchPt": "Criar no Scratch uma tela com botão, personagem ou fluxo simples que represente a solução."
        },
        {
          "id": "rural-youth-13",
          "phase": 13,
          "title": "Apresentação",
          "icon": "🎪",
          "goal": "apresentar a solução para a comunidade",
          "storyPt": "Hoje a turma abre uma portinha nova: olhar para previsão de chuva com olhos de quem cuida, pergunta e cria. A ideia não é acertar de primeira. É reparar, testar e melhorar.",
          "screenPt": "Registre hipóteses, evidências e decisões no painel do projeto. Depois escolha uma ação pequena para validar.",
          "offlinePt": "Observe previsão de chuva por 10 minutos sem celular. Anote no caderno: o que funciona, o que atrapalha e quem poderia ajudar.",
          "reflectionPt": "O que descobrimos que não sabíamos antes?",
          "aiPrepPt": "Peça ajuda da IA para organizar ideias, mas a decisão final precisa ser do time.",
          "badgePt": "Olhar Curioso",
          "scratchPt": "Criar no Scratch uma tela com botão, personagem ou fluxo simples que represente a solução."
        },
        {
          "id": "rural-youth-14",
          "phase": 14,
          "title": "E agora?",
          "icon": "🚀",
          "goal": "planejar próximos passos e celebrar aprendizados",
          "storyPt": "Hoje a turma abre uma portinha nova: olhar para feira de produtores com olhos de quem cuida, pergunta e cria. A ideia não é acertar de primeira. É reparar, testar e melhorar.",
          "screenPt": "Registre hipóteses, evidências e decisões no painel do projeto. Depois escolha uma ação pequena para validar.",
          "offlinePt": "Observe feira de produtores por 10 minutos sem celular. Anote no caderno: o que funciona, o que atrapalha e quem poderia ajudar.",
          "reflectionPt": "O que descobrimos que não sabíamos antes?",
          "aiPrepPt": "Peça ajuda da IA para organizar ideias, mas a decisão final precisa ser do time.",
          "badgePt": "Mão na Massa",
          "scratchPt": "Criar no Scratch uma tela com botão, personagem ou fluxo simples que represente a solução."
        }
      ]
    },
    {
      "id": "urban-youth",
      "age": "12-14",
      "context": "urban",
      "pt": "Jovens Inovadores da Cidade",
      "en": "Young City Innovators",
      "es": "Jóvenes Innovadores de la Ciudad",
      "tone": "direto, curioso, com desafios de bairro, mobilidade, consumo consciente, serviços, escola e cultura digital",
      "missions": [
        {
          "id": "urban-youth-1",
          "phase": 1,
          "title": "Largada",
          "icon": "🚜",
          "goal": "entrar na jornada e entender que empreender é observar problemas e criar soluções úteis",
          "storyPt": "Hoje a turma abre uma portinha nova: olhar para mobilidade no bairro com olhos de quem cuida, pergunta e cria. A ideia não é acertar de primeira. É reparar, testar e melhorar.",
          "screenPt": "Registre hipóteses, evidências e decisões no painel do projeto. Depois escolha uma ação pequena para validar.",
          "offlinePt": "Observe mobilidade no bairro por 10 minutos sem celular. Anote no caderno: o que funciona, o que atrapalha e quem poderia ajudar.",
          "reflectionPt": "O que descobrimos que não sabíamos antes?",
          "aiPrepPt": "Ainda sem pedir resposta pronta para a IA: primeiro a turma observa e pergunta.",
          "badgePt": "Olhar Curioso",
          "scratchPt": "Usar Scratch só como desenho animado simples para contar o problema, se fizer sentido."
        },
        {
          "id": "urban-youth-2",
          "phase": 2,
          "title": "O que é empreender",
          "icon": "💡",
          "goal": "separar mito de realidade sobre empreender e valorizar persistência",
          "storyPt": "Hoje a turma abre uma portinha nova: olhar para desperdício de alimentos com olhos de quem cuida, pergunta e cria. A ideia não é acertar de primeira. É reparar, testar e melhorar.",
          "screenPt": "Registre hipóteses, evidências e decisões no painel do projeto. Depois escolha uma ação pequena para validar.",
          "offlinePt": "Observe desperdício de alimentos por 10 minutos sem celular. Anote no caderno: o que funciona, o que atrapalha e quem poderia ajudar.",
          "reflectionPt": "O que descobrimos que não sabíamos antes?",
          "aiPrepPt": "Ainda sem pedir resposta pronta para a IA: primeiro a turma observa e pergunta.",
          "badgePt": "Mão na Massa",
          "scratchPt": "Usar Scratch só como desenho animado simples para contar o problema, se fizer sentido."
        },
        {
          "id": "urban-youth-3",
          "phase": 3,
          "title": "Simulador",
          "icon": "🧭",
          "goal": "simular escolhas, consequências e combinados de equipe",
          "storyPt": "Hoje a turma abre uma portinha nova: olhar para agenda de estudos com olhos de quem cuida, pergunta e cria. A ideia não é acertar de primeira. É reparar, testar e melhorar.",
          "screenPt": "Registre hipóteses, evidências e decisões no painel do projeto. Depois escolha uma ação pequena para validar.",
          "offlinePt": "Observe agenda de estudos por 10 minutos sem celular. Anote no caderno: o que funciona, o que atrapalha e quem poderia ajudar.",
          "reflectionPt": "O que descobrimos que não sabíamos antes?",
          "aiPrepPt": "Ainda sem pedir resposta pronta para a IA: primeiro a turma observa e pergunta.",
          "badgePt": "Escuta Atenta",
          "scratchPt": "Usar Scratch só como desenho animado simples para contar o problema, se fizer sentido."
        },
        {
          "id": "urban-youth-4",
          "phase": 4,
          "title": "Desafios e times",
          "icon": "🤝",
          "goal": "formar times, escolher papéis e descobrir desafios próximos",
          "storyPt": "Hoje a turma abre uma portinha nova: olhar para serviços locais com olhos de quem cuida, pergunta e cria. A ideia não é acertar de primeira. É reparar, testar e melhorar.",
          "screenPt": "Registre hipóteses, evidências e decisões no painel do projeto. Depois escolha uma ação pequena para validar.",
          "offlinePt": "Observe serviços locais por 10 minutos sem celular. Anote no caderno: o que funciona, o que atrapalha e quem poderia ajudar.",
          "reflectionPt": "O que descobrimos que não sabíamos antes?",
          "aiPrepPt": "Ainda sem pedir resposta pronta para a IA: primeiro a turma observa e pergunta.",
          "badgePt": "Ideia Brotando",
          "scratchPt": "Usar Scratch só como desenho animado simples para contar o problema, se fizer sentido."
        },
        {
          "id": "urban-youth-5",
          "phase": 5,
          "title": "Empatia: ativar",
          "icon": "👂",
          "goal": "conversar com pessoas de verdade antes de inventar soluções",
          "storyPt": "Hoje a turma abre uma portinha nova: olhar para cultura e eventos com olhos de quem cuida, pergunta e cria. A ideia não é acertar de primeira. É reparar, testar e melhorar.",
          "screenPt": "Registre hipóteses, evidências e decisões no painel do projeto. Depois escolha uma ação pequena para validar.",
          "offlinePt": "Converse com alguém da família ou da comunidade sobre cultura e eventos. Traga uma frase, um desenho ou uma foto autorizada que mostre uma necessidade real.",
          "reflectionPt": "O que descobrimos que não sabíamos antes?",
          "aiPrepPt": "Ainda sem pedir resposta pronta para a IA: primeiro a turma observa e pergunta.",
          "badgePt": "Teste Corajoso",
          "scratchPt": "Usar Scratch só como desenho animado simples para contar o problema, se fizer sentido."
        },
        {
          "id": "urban-youth-6",
          "phase": 6,
          "title": "Insights",
          "icon": "🔎",
          "goal": "transformar escutas em descobertas claras",
          "storyPt": "Hoje a turma abre uma portinha nova: olhar para mobilidade no bairro com olhos de quem cuida, pergunta e cria. A ideia não é acertar de primeira. É reparar, testar e melhorar.",
          "screenPt": "Registre hipóteses, evidências e decisões no painel do projeto. Depois escolha uma ação pequena para validar.",
          "offlinePt": "Converse com alguém da família ou da comunidade sobre mobilidade no bairro. Traga uma frase, um desenho ou uma foto autorizada que mostre uma necessidade real.",
          "reflectionPt": "O que descobrimos que não sabíamos antes?",
          "aiPrepPt": "Ainda sem pedir resposta pronta para a IA: primeiro a turma observa e pergunta.",
          "badgePt": "Voz de Projeto",
          "scratchPt": "Usar Scratch só como desenho animado simples para contar o problema, se fizer sentido."
        },
        {
          "id": "urban-youth-7",
          "phase": 7,
          "title": "Tendo ideias",
          "icon": "🌱",
          "goal": "gerar muitas ideias e escolher uma com critérios simples",
          "storyPt": "Hoje a turma abre uma portinha nova: olhar para desperdício de alimentos com olhos de quem cuida, pergunta e cria. A ideia não é acertar de primeira. É reparar, testar e melhorar.",
          "screenPt": "Registre hipóteses, evidências e decisões no painel do projeto. Depois escolha uma ação pequena para validar.",
          "offlinePt": "Observe desperdício de alimentos por 10 minutos sem celular. Anote no caderno: o que funciona, o que atrapalha e quem poderia ajudar.",
          "reflectionPt": "O que descobrimos que não sabíamos antes?",
          "aiPrepPt": "Ainda sem pedir resposta pronta para a IA: primeiro a turma observa e pergunta.",
          "badgePt": "Olhar Curioso",
          "scratchPt": "Usar Scratch só como desenho animado simples para contar o problema, se fizer sentido."
        },
        {
          "id": "urban-youth-8",
          "phase": 8,
          "title": "Protótipo",
          "icon": "🛠️",
          "goal": "criar um primeiro protótipo em papel, Scratch ou encenação",
          "storyPt": "Hoje a turma abre uma portinha nova: olhar para agenda de estudos com olhos de quem cuida, pergunta e cria. A ideia não é acertar de primeira. É reparar, testar e melhorar.",
          "screenPt": "Registre hipóteses, evidências e decisões no painel do projeto. Depois escolha uma ação pequena para validar.",
          "offlinePt": "Observe agenda de estudos por 10 minutos sem celular. Anote no caderno: o que funciona, o que atrapalha e quem poderia ajudar.",
          "reflectionPt": "O que descobrimos que não sabíamos antes?",
          "aiPrepPt": "Peça ajuda da IA para organizar ideias, mas a decisão final precisa ser do time.",
          "badgePt": "Mão na Massa",
          "scratchPt": "Criar no Scratch uma tela com botão, personagem ou fluxo simples que represente a solução."
        },
        {
          "id": "urban-youth-9",
          "phase": 9,
          "title": "Canvas",
          "icon": "🗺️",
          "goal": "organizar proposta de valor, público, recursos e parceiros",
          "storyPt": "Hoje a turma abre uma portinha nova: olhar para serviços locais com olhos de quem cuida, pergunta e cria. A ideia não é acertar de primeira. É reparar, testar e melhorar.",
          "screenPt": "Registre hipóteses, evidências e decisões no painel do projeto. Depois escolha uma ação pequena para validar.",
          "offlinePt": "Observe serviços locais por 10 minutos sem celular. Anote no caderno: o que funciona, o que atrapalha e quem poderia ajudar.",
          "reflectionPt": "O que descobrimos que não sabíamos antes?",
          "aiPrepPt": "Peça ajuda da IA para organizar ideias, mas a decisão final precisa ser do time.",
          "badgePt": "Escuta Atenta",
          "scratchPt": "Criar no Scratch uma tela com botão, personagem ou fluxo simples que represente a solução."
        },
        {
          "id": "urban-youth-10",
          "phase": 10,
          "title": "Aprendendo com os testes",
          "icon": "🧪",
          "goal": "testar com usuários, ouvir críticas e melhorar sem drama",
          "storyPt": "Hoje a turma abre uma portinha nova: olhar para cultura e eventos com olhos de quem cuida, pergunta e cria. A ideia não é acertar de primeira. É reparar, testar e melhorar.",
          "screenPt": "Registre hipóteses, evidências e decisões no painel do projeto. Depois escolha uma ação pequena para validar.",
          "offlinePt": "Converse com alguém da família ou da comunidade sobre cultura e eventos. Traga uma frase, um desenho ou uma foto autorizada que mostre uma necessidade real.",
          "reflectionPt": "O que descobrimos que não sabíamos antes?",
          "aiPrepPt": "Peça ajuda da IA para organizar ideias, mas a decisão final precisa ser do time.",
          "badgePt": "Ideia Brotando",
          "scratchPt": "Criar no Scratch uma tela com botão, personagem ou fluxo simples que represente a solução."
        },
        {
          "id": "urban-youth-11",
          "phase": 11,
          "title": "Mutirão de criação",
          "icon": "⚡",
          "goal": "melhorar o protótipo em ritmo de mutirão",
          "storyPt": "Hoje a turma abre uma portinha nova: olhar para mobilidade no bairro com olhos de quem cuida, pergunta e cria. A ideia não é acertar de primeira. É reparar, testar e melhorar.",
          "screenPt": "Registre hipóteses, evidências e decisões no painel do projeto. Depois escolha uma ação pequena para validar.",
          "offlinePt": "Observe mobilidade no bairro por 10 minutos sem celular. Anote no caderno: o que funciona, o que atrapalha e quem poderia ajudar.",
          "reflectionPt": "O que descobrimos que não sabíamos antes?",
          "aiPrepPt": "Peça ajuda da IA para organizar ideias, mas a decisão final precisa ser do time.",
          "badgePt": "Teste Corajoso",
          "scratchPt": "Criar no Scratch uma tela com botão, personagem ou fluxo simples que represente a solução."
        },
        {
          "id": "urban-youth-12",
          "phase": 12,
          "title": "Preparando a apresentação",
          "icon": "🎤",
          "goal": "preparar uma fala curta, clara e honesta",
          "storyPt": "Hoje a turma abre uma portinha nova: olhar para desperdício de alimentos com olhos de quem cuida, pergunta e cria. A ideia não é acertar de primeira. É reparar, testar e melhorar.",
          "screenPt": "Registre hipóteses, evidências e decisões no painel do projeto. Depois escolha uma ação pequena para validar.",
          "offlinePt": "Observe desperdício de alimentos por 10 minutos sem celular. Anote no caderno: o que funciona, o que atrapalha e quem poderia ajudar.",
          "reflectionPt": "O que descobrimos que não sabíamos antes?",
          "aiPrepPt": "Peça ajuda da IA para organizar ideias, mas a decisão final precisa ser do time.",
          "badgePt": "Voz de Projeto",
          "scratchPt": "Criar no Scratch uma tela com botão, personagem ou fluxo simples que represente a solução."
        },
        {
          "id": "urban-youth-13",
          "phase": 13,
          "title": "Apresentação",
          "icon": "🎪",
          "goal": "apresentar a solução para a comunidade",
          "storyPt": "Hoje a turma abre uma portinha nova: olhar para agenda de estudos com olhos de quem cuida, pergunta e cria. A ideia não é acertar de primeira. É reparar, testar e melhorar.",
          "screenPt": "Registre hipóteses, evidências e decisões no painel do projeto. Depois escolha uma ação pequena para validar.",
          "offlinePt": "Observe agenda de estudos por 10 minutos sem celular. Anote no caderno: o que funciona, o que atrapalha e quem poderia ajudar.",
          "reflectionPt": "O que descobrimos que não sabíamos antes?",
          "aiPrepPt": "Peça ajuda da IA para organizar ideias, mas a decisão final precisa ser do time.",
          "badgePt": "Olhar Curioso",
          "scratchPt": "Criar no Scratch uma tela com botão, personagem ou fluxo simples que represente a solução."
        },
        {
          "id": "urban-youth-14",
          "phase": 14,
          "title": "E agora?",
          "icon": "🚀",
          "goal": "planejar próximos passos e celebrar aprendizados",
          "storyPt": "Hoje a turma abre uma portinha nova: olhar para serviços locais com olhos de quem cuida, pergunta e cria. A ideia não é acertar de primeira. É reparar, testar e melhorar.",
          "screenPt": "Registre hipóteses, evidências e decisões no painel do projeto. Depois escolha uma ação pequena para validar.",
          "offlinePt": "Observe serviços locais por 10 minutos sem celular. Anote no caderno: o que funciona, o que atrapalha e quem poderia ajudar.",
          "reflectionPt": "O que descobrimos que não sabíamos antes?",
          "aiPrepPt": "Peça ajuda da IA para organizar ideias, mas a decisão final precisa ser do time.",
          "badgePt": "Mão na Massa",
          "scratchPt": "Criar no Scratch uma tela com botão, personagem ou fluxo simples que represente a solução."
        }
      ]
    }
  ],
  "manuals": {
    "achiever": "content/manuals/manual-achiever-extraido-pt.txt",
    "adviser": "content/manuals/manual-adviser-extraido-pt.txt"
  }
} as const;
