export type RuralPhaseSupport = {
  phase: number;
  chapter: 'Abrir os olhos' | 'Escutar quem vive aqui' | 'Fazer e melhorar' | 'Devolver para a comunidade';
  icon: string;
  childCall: string;
  childMove: string;
  evidence: string;
  facilitatorGoal: string;
  duration: string;
  prepare: string;
  ask: string;
  watch: string;
  behavior: string;
};

export const ruralChapters = [
  {
    title: 'Abrir os olhos',
    phases: '1–4',
    icon: '🔎',
    text: 'A turma percebe que o lugar onde vive guarda perguntas, saberes e pequenos desafios.',
  },
  {
    title: 'Escutar quem vive aqui',
    phases: '5–7',
    icon: '👂',
    text: 'Palpites encontram pessoas reais, histórias locais e pistas que mudam a primeira ideia.',
  },
  {
    title: 'Fazer e melhorar',
    phases: '8–11',
    icon: '🛠️',
    text: 'O grupo constrói com o que tem, testa pequeno e transforma crítica em melhoria.',
  },
  {
    title: 'Devolver para a comunidade',
    phases: '12–14',
    icon: '📻',
    text: 'A descoberta volta para a comunidade em forma de história, demonstração e próximo combinado.',
  },
] as const;

export const ruralPhaseSupport: RuralPhaseSupport[] = [
  {
    phase: 1,
    chapter: 'Abrir os olhos',
    icon: '🗺️',
    childCall: 'Nossa Terra tem pistas. Qual delas chama a nossa atenção?',
    childMove: 'Desenhe o caminho entre casa, escola e um lugar importante da comunidade. Marque algo que funciona bem e algo que desperta curiosidade.',
    evidence: 'Mapa afetivo com um lugar, uma pessoa e uma pergunta.',
    facilitatorGoal: 'Criar pertencimento e mostrar que o território já contém conhecimento e oportunidades de investigação.',
    duration: '45–60 min',
    prepare: 'Papel grande, lápis de cor, adesivos ou sementes secas para marcar lugares.',
    ask: 'Que lugar você mostraria primeiro para alguém que chegou hoje por aqui?',
    watch: 'Não reduzir rural a lavoura. Acolher praça, comércio, escola, estrada, oficina, posto, rio, quintal e memória familiar.',
    behavior: 'Iniciativa: escolhe uma pista e explica por que vale olhar de novo.',
  },
  {
    phase: 2,
    chapter: 'Abrir os olhos',
    icon: '🤲',
    childCall: 'Quem faz o lugar onde a gente vive funcionar quando quase ninguém está olhando?',
    childMove: 'Escolha uma pessoa que planta, cuida, conserta, vende, ensina, transporta ou organiza. Descubra qual ajuda ela entrega.',
    evidence: 'Retrato desenhado e frase “essa pessoa ajuda quando…”.',
    facilitatorGoal: 'Ampliar empreendedorismo para criação de valor e cuidado, sem antecipar empresa, lucro ou profissão.',
    duration: '40–50 min',
    prepare: 'Cartões com ações: cuidar, consertar, plantar, ensinar, levar, vender, organizar, informar.',
    ask: 'O que ficaria mais difícil se essa pessoa parasse de fazer seu trabalho por uma semana?',
    watch: 'Evitar eleger apenas figuras de maior status. Tornar visível o trabalho cotidiano e comunitário.',
    behavior: 'Busca de oportunidade: percebe uma ajuda concreta que melhora a vida de alguém.',
  },
  {
    phase: 3,
    chapter: 'Abrir os olhos',
    icon: '🎲',
    childCall: 'Choveu, a estrada mudou e a feira começa cedo. O que fazemos primeiro?',
    childMove: 'Jogue uma rodada de escolhas com cartas de imprevisto. O grupo escolhe, explica e vê a consequência.',
    evidence: 'Uma decisão, seu motivo e o que o grupo faria diferente.',
    facilitatorGoal: 'Praticar decisão sob incerteza com consequências leves e reversíveis.',
    duration: '45–60 min',
    prepare: 'Cartas de clima, transporte, falta de material, ajuda inesperada e mudança de horário.',
    ask: 'Que pista ajudou vocês a decidir sem ter certeza de tudo?',
    watch: 'Não premiar rapidez. Valorizar quem pergunta, compara opções e muda de ideia com uma pista nova.',
    behavior: 'Risco calculado: escolhe uma opção possível e explica o cuidado adotado.',
  },
  {
    phase: 4,
    chapter: 'Abrir os olhos',
    icon: '🧶',
    childCall: 'Uma boa equipe não precisa de chefe para tudo. Quem segura cada parte?',
    childMove: 'Distribua fichas de papel: quem pergunta, observa, desenha, cuida do tempo e conta a descoberta. Troque os papéis na metade.',
    evidence: 'Acordo do grupo com papéis, regra de escuta e desafio escolhido.',
    facilitatorGoal: 'Criar segurança de colaboração, participação e responsabilidade compartilhada.',
    duration: '50–60 min',
    prepare: 'Fichas coloridas de papéis, barbante e um cartaz “como queremos trabalhar”.',
    ask: 'Qual parte quase ficou esquecida? Quem percebeu e pediu ajuda?',
    watch: 'Impedir que leitura, escrita ou extroversão virem poder fixo. Rodar papéis e oferecer formas diferentes de contribuir.',
    behavior: 'Comprometimento: assume uma parte visível e ajuda o grupo a cumprir o combinado.',
  },
  {
    phase: 5,
    chapter: 'Escutar quem vive aqui',
    icon: '👂',
    childCall: 'Antes de inventar, vamos escutar quem vive isso de verdade.',
    childMove: 'Prepare três perguntas curtas e converse com alguém da comunidade. Escute uma história sem completar a frase da pessoa.',
    evidence: 'Uma fala autorizada, um desenho da situação e uma surpresa.',
    facilitatorGoal: 'Trocar opinião por escuta respeitosa e investigação da experiência de outra pessoa.',
    duration: '60–90 min',
    prepare: 'Roteiro de consentimento, três cartões-pergunta e alternativa sem foto ou áudio.',
    ask: 'O que apareceu na fala da pessoa que não estava no nosso palpite?',
    watch: 'Proteger privacidade e evitar perguntas invasivas. Criança não entrevista sozinha fora do espaço combinado.',
    behavior: 'Busca de informação: faz pergunta, escuta e registra uma pista relevante.',
  },
  {
    phase: 6,
    chapter: 'Escutar quem vive aqui',
    icon: '🧺',
    childCall: 'Temos um balaio de pistas. Quais combinam? Qual delas contradiz as outras?',
    childMove: 'Separe cartões em “vimos”, “ouvimos”, “achávamos” e “ainda precisamos descobrir”.',
    evidence: 'Painel de pistas com uma mudança de opinião marcada.',
    facilitatorGoal: 'Ensinar a diferença entre observação, relato, hipótese e lacuna sem transformar a atividade em aula abstrata.',
    duration: '45–60 min',
    prepare: 'Quatro cestos, envelopes ou áreas no chão e cartões dos registros da fase anterior.',
    ask: 'Qual palpite ficou mais fraco depois que apareceu uma pista real?',
    watch: 'Não forçar consenso. Divergências honestas podem virar a próxima pergunta.',
    behavior: 'Qualidade e eficiência: organiza informações antes de escolher um caminho.',
  },
  {
    phase: 7,
    chapter: 'Escutar quem vive aqui',
    icon: '🌱',
    childCall: 'Uma pista pode virar muitas ideias. Vamos plantar pelo menos três.',
    childMove: 'Crie três respostas pequenas: uma que usa quase nada, uma feita em mutirão e uma ideia inesperada. Escolha pela possibilidade de testar.',
    evidence: 'Três sementes de ideia e uma escolha com critério.',
    facilitatorGoal: 'Separar geração de escolha e evitar que a primeira ideia ou a voz mais alta domine.',
    duration: '50–70 min',
    prepare: 'Cartões em forma de sementes e critérios visuais: ajuda alguém, cabe no tempo, usa o que temos, dá para testar.',
    ask: 'Qual ideia ensina mais mesmo se não funcionar de primeira?',
    watch: 'Manter espaço para desenho, fala, montagem e gesto. Escrita não pode ser a única porta de participação.',
    behavior: 'Persistência: cria alternativas antes de desistir ou se apegar à primeira solução.',
  },
  {
    phase: 8,
    chapter: 'Fazer e melhorar',
    icon: '🧰',
    childCall: 'A primeira versão pode ser feia. Ela só precisa conseguir conversar.',
    childMove: 'Construa com papelão, barbante, sucata limpa, argila, desenho, encenação ou Scratch simples.',
    evidence: 'Protótipo de baixa fidelidade e frase “queremos descobrir se…”.',
    facilitatorGoal: 'Transformar pensamento em objeto criticável sem premiar acabamento precoce.',
    duration: '70–90 min',
    prepare: 'Caixa de materiais locais seguros, fita, tesoura sem ponta e mesa de peças reutilizáveis.',
    ask: 'O que precisa funcionar para o teste, e o que pode continuar de mentira por enquanto?',
    watch: 'Adultos não devem construir pela criança. Ajudar com segurança, corte difícil e perguntas.',
    behavior: 'Planejamento: define um resultado pequeno e organiza recursos para construí-lo.',
  },
  {
    phase: 9,
    chapter: 'Fazer e melhorar',
    icon: '🛤️',
    childCall: 'Toda ideia percorre um caminho. Quem ajuda, o que precisa e onde pode emperrar?',
    childMove: 'Monte um mapa com pessoa ajudada, momento de uso, materiais, parceiros e caminho até a solução.',
    evidence: 'Mapa do caminho da ideia com pelo menos um parceiro local.',
    facilitatorGoal: 'Introduzir visão de sistema e recursos com linguagem territorial, sem Business Model Canvas adulto.',
    duration: '50–70 min',
    prepare: 'Cartões de pessoa, lugar, material, tempo, parceiro e cuidado.',
    ask: 'Que parte do caminho depende de alguém que ainda não escutamos?',
    watch: 'Não reduzir valor a dinheiro. Tempo poupado, segurança, pertencimento, cuidado e orgulho também contam.',
    behavior: 'Planejamento e rede: identifica recursos e pede uma ajuda específica.',
  },
  {
    phase: 10,
    chapter: 'Fazer e melhorar',
    icon: '🧪',
    childCall: 'Teste não é apresentação. É uma chance de alguém mostrar onde a ideia tropeça.',
    childMove: 'Mostre o protótipo para uma pessoa. Observe antes de explicar. Depois faça duas perguntas curtas.',
    evidence: 'Uma reação observada, uma crítica e uma mudança decidida.',
    facilitatorGoal: 'Criar segurança para receber crítica como informação, não como julgamento da criança.',
    duration: '60–80 min',
    prepare: 'Roteiro de teste, autorização, ficha “funcionou / confundiu / faltou”.',
    ask: 'O que a pessoa fez de verdade, diferente do que vocês esperavam?',
    watch: 'Interromper deboche ou defesa agressiva. Modelar agradecimento e curiosidade diante do erro.',
    behavior: 'Persuasão e aprendizagem: apresenta com clareza e usa retorno real para ajustar.',
  },
  {
    phase: 11,
    chapter: 'Fazer e melhorar',
    icon: '🤝',
    childCall: 'Dia de mutirão: cada ajuda tem nome, tempo e destino.',
    childMove: 'Organize estações de conserto, clareza, teste e história. Cada grupo pede e oferece uma ajuda específica.',
    evidence: 'Antes e depois do protótipo, com registro de quem ajudou em quê.',
    facilitatorGoal: 'Praticar rede de colaboração, negociação de ajuda e melhoria concentrada.',
    duration: '80–120 min',
    prepare: 'Estações sinalizadas, materiais, relógio visível e quadro de pedidos/ofertas.',
    ask: 'Que ajuda destravou o trabalho sem tirar a autoria do grupo?',
    watch: 'Evitar competição de acabamento. Reconhecer trocas, pedidos claros e cuidado com materiais.',
    behavior: 'Rede de contatos: oferece, pede e reconhece contribuições concretas.',
  },
  {
    phase: 12,
    chapter: 'Devolver para a comunidade',
    icon: '🎙️',
    childCall: 'Uma boa história mostra a pergunta, a pista, a tentativa e a mudança.',
    childMove: 'Monte uma fala de um minuto ou uma pequena reportagem para a rádio da turma.',
    evidence: 'Roteiro com quatro cenas e participação de todas as crianças.',
    facilitatorGoal: 'Organizar comunicação honesta sem apagar dúvidas, erros ou autoria coletiva.',
    duration: '50–70 min',
    prepare: 'Cartões “pergunta / pista / tentativa / mudança”, cronômetro e gravador opcional.',
    ask: 'O que aprendemos que não sabíamos no começo?',
    watch: 'Não transformar a criança mais falante em porta-voz permanente. Distribuir fala, demonstração, desenho e acolhida.',
    behavior: 'Persuasão: comunica valor e evidência sem prometer mais do que foi testado.',
  },
  {
    phase: 13,
    chapter: 'Devolver para a comunidade',
    icon: '🎪',
    childCall: 'A oficina abre as portas. A comunidade vem perguntar, experimentar e melhorar junto.',
    childMove: 'Apresente em formato de feira: uma pessoa acolhe, outra conta a pista, outra demonstra e outra registra retornos.',
    evidence: 'Demonstração, perguntas recebidas e mural de devolutivas.',
    facilitatorGoal: 'Celebrar autoria e devolver conhecimento ao território, não simular banca de investidores.',
    duration: '60–90 min',
    prepare: 'Mesas ou cantos de demonstração, convites simples, consentimentos e mural de feedback.',
    ask: 'Que pergunta da comunidade abriu uma ideia nova?',
    watch: 'Proteger crianças de exposição, comparação pública e comentários humilhantes. Preparar adultos convidados para feedback respeitoso.',
    behavior: 'Autoconfiança responsável: apresenta o que sabe, admite limites e responde com respeito.',
  },
  {
    phase: 14,
    chapter: 'Devolver para a comunidade',
    icon: '🌾',
    childCall: 'O que fica plantado depois que a aventura termina?',
    childMove: 'Escolha uma coisa para manter, uma para mudar, uma para parar e um próximo cuidado possível nas próximas duas semanas.',
    evidence: 'Carta para o futuro com decisão, responsável, data e primeira ação.',
    facilitatorGoal: 'Fechar com transferência para a vida real, metacognição e compromisso pequeno, não com promessa abstrata.',
    duration: '45–60 min',
    prepare: 'Cartas dobráveis, envelopes, sementes simbólicas ou carimbos de evidência.',
    ask: 'Que jeito de observar, escutar ou testar você consegue usar amanhã?',
    watch: 'Não pressionar continuidade de todo protótipo. Parar com justificativa também pode ser uma decisão madura.',
    behavior: 'Metas: escolhe um próximo passo específico, possível e verificável.',
  },
];

export function getRuralPhaseSupport(phase: number) {
  return ruralPhaseSupport.find((item) => item.phase === phase) ?? ruralPhaseSupport[0];
}
